= Problem Details
:toc: preamble
:numbered:
:icons: font

image:https://api.bintray.com/packages/t1/javaee-helpers/problem-details/images/download.svg[link="https://bintray.com/t1/javaee-helpers/problem-details/_latestVersion"]
image:https://github.com/t1/problem-details/workflows/Java%20CI/badge.svg[Java CI]

== Intro

Implements the https://github.com/eclipse/microprofile-sandbox/blob/master/proposals/problem-details/spec/src/main/asciidoc/microprofile-problemdetails.asciidoc[Microprofile Problem Detail Spec] to map standard and custom exceptions to http response bodies containing problem details as specified in https://tools.ietf.org/html/rfc7807[RFC-7807] and/or convert and throw problem details as exceptions on the client side. Both for JAX-RS as well as Spring Boot.

Why would you? See https://blog.codecentric.de/en/2020/01/rfc-7807-problem-details-with-spring-boot-and-jax-rs/[this blog post].

== Quick Start

Say you have a custom business exception to tell the client that the order just posted was above the credit range granted to the customer.

[source,java]
---------------------------------------------------------------
public class OutOfCreditException extends RuntimeException {}
---------------------------------------------------------------

Throwing this will produce a 500 Internal Server Error with some html page that includes the stack trace. The client _could_ search for this exception in the stack trace and display a corresponding message to the customer... but that's not what we _want_ to do.

Add a dependency on `io.microprofile.sandbox:problem-details-api` and a runtime dependency on `com.github.t1:problem-details-ri` for JAX-RS applications and `com.github.t1:problem-details-ri-spring` for Spring applications.

Now throwing the same exception will result in an exception body with a `Content-Type` header `application/problem+json` similar to this:

[source,yaml]
---------------------------------------------------------------
{
  "type": "urn:problem-type:out-of-credit",                   # <1>
  "title": "Out Of Credit",                                   # <2>
  "status": 400,                                              # <3>
  "instance": "urn:uuid:d294b32b-9dda-4292-b51f-35f65b4bf64d" # <4>
}
---------------------------------------------------------------

<1> The default `type` is a URN derived from the type name of the exception by converting camel case to kebap case and stripping the `Exception`.
<2> The default `title` is derived from the type name of the exception by converting camel case to separate words.
<3> The default `status` is `400 Bad Request` except for custom exceptions.
<4> The default `instance` is a random UUID URN.

There's no stack trace in the response any more, so we don't expose details about our service that could be interesting to a potential adversary. But we can use the `instance` field to search our server logs, so we can see this failure in the context of all the other logs produced for the request.

On the client side, we can use the `type` field to react in a sensible manner. But we can do even better: by adding the same dependencies on the client side, the problem detail is converted back to an exception. E.g. when using the MicroProfile Rest Client, the code can look like this:

[source,java]
---------------------------------------------------------------
public class OrderGateway {

    @RegisterRestClient
    interface OrderApi {
        @Path("/orders/{article-id}")
        @POST Shipment order(@PathParam("article-id") String articleId)
            throws OutOfCreditException;
    }

    @Inject @RestClient OrderApi orderApi;

    public Shipment order(String articleId) {
        try {
            return orderApi.order(articleId);
        } catch (OutOfCreditException e) {
            handleOutOfCredit();
            return null;
        }
    }
}
---------------------------------------------------------------

Note that the `OutOfCreditException` doesn't have to be exactly the same, it just has to have the same simple class name, but can be in a different package, have different constructors, etc.

Maybe we want to have more control over the problem detail. E.g. we may want to have a status code `403 Forbidden`, a different `title`, and the client needs to display the current balance, so we need a `balance` field.

[source,java]
---------------------------------------------------------------
@Status(FORBIDDEN)
@Title("You do not have enough credit.")
public class OutOfCreditException extends RuntimeException {
    @Extension private int balance;
}
---------------------------------------------------------------

This will produce a problem detail like this:

[source,yaml]
---------------------------------------------------------------
{
  "type": "urn:problem-type:out-of-credit",
  "title": "You do not have enough credit.",
  "status": 403,
  "instance": "urn:uuid:d294b32b-9dda-4292-b51f-35f65b4bf64d",
  "balance": 50
}
---------------------------------------------------------------

There are many other nice features. For the full documentation, look at the https://github.com/eclipse/microprofile-sandbox/blob/master/proposals/problem-details/spec/src/main/asciidoc/microprofile-problemdetails.asciidoc[MP spec] and/or the https://tools.ietf.org/html/rfc7807[RFC-7807] for the exact semantics of those fields.

== Implementation Details

1. We use http://www.slf4j.org[slf4j] for logging. If this is not provided by your application server, you may also have to package the `slf4j-api` and a binding like `slf4j-jdk14`.

== Module Structure

=== ri

A JAX-RS implementation, called `ri` even though it's actually only a POC, and it's incomplete. See the README for details.

=== ri-spring

A Spring Boot implementation. This also is just a POC, there may be better integration points that I'm not aware of.

=== ri-lib

This is a library used by the JAX-RS RI as well as the Spring RI. It's not part of any supported public API, so you MUST NOT depend on this module directly.

=== ri-demo

Builds a `war` hard-wired to the `ri`; and when using the maven profile `with-slf4j`, the `slf4j-api` and `slf4j-jdk14` are included as well. The integration tests use https://github.com/t1/jee-testcontainers[JEE Testcontainers], i.e. it can be configured to start different Docker containers with various JEE application servers (details below). By default, it starts a Wildfly.

You can also specify a base URL in the system property `testcontainer-running` (e.g. `-Dtestcontainer-running=http://localhost:8080/ri-demo`), so the tests verify a running service. This is very handy while developing. This also works when the running service is the Spring Boot Test application (see below).

==== Wildfly

Default `mvn` or explicitly `mvn -Djee-testcontainer=wildfly`

==== Open Liberty

`mvn -Djee-testcontainer=open-liberty:full -Pwith-slf4j`

==== TomEE

`mvn -Djee-testcontainer=tomee`

The `latest` image is outdated. TomEE 8.0.0 was released on 2019-09-16, but the image is still 8.0.0-M3.

This version doesn't write the problem detail response entity in some cases I don't understand.

==== Payara

`mvn -Djee-testcontainer=payara -Pwith-slf4j`

=== test-spring

Builds a Spring Boot application containing the RI. The integration tests also start the application.

You can specify a base URL in the system property `testcontainer-running` (e.g. `-Dtestcontainer-running=http://localhost:8080`), so the tests verify a running service. This is very handy while developing the implementation. This also works when the running service is the JAX-RS Test application (see above).
