name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [ 11, 17 ]

    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
    - uses: actions/setup-java@v3
      with:
        java-version: ${{matrix.jdk}}
        distribution: 'temurin'
        cache: 'maven'
    - run: mvn --batch-mode --show-version --no-transfer-progress -DCI=GitHub install
